# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'dsc-sahmyook'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-162533543-1'

menu: 
  # - name: Featured Projects
  #   submenu:
  #     - name: MicroBam
  #       link: /projects/microbam
  #     - name: OurLegacy
  #       link: /projects/ourlegacy
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  # - name: About
  #   link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/DSC-Sahmyook
      # - name: LinkedIn
      #   icon: linkedin-square
      #   link: http://www.linkedin.com/in/alainpham
      # - name: Twitter
      #   icon: twitter
      #   link: https://twitter.com/koint
    
